### ISSUE TITLE
component fails to compile on ESPHome 2025.11 (FixedVector copy error)

### ISSUE THREAD

**Issue by plplaaa2** [dhewg/esphome-miot#90]
Environment
ESPHome version: 2025.11

Platform: ESP32 (PlatformIO)

```
src/esphome/components/miot/select/miot_select.cpp: In lambda function:
src/esphome/components/miot/select/miot_select.cpp:13:45: error: use of deleted function 'esphome::FixedVector<T>::FixedVector(const esphome::FixedVector<T>&) [with T = const char*]'
   13 |     auto options = this->traits.get_options();
      |                                             ^
In file included from src/esphome/components/json/json_util.h:6,
                 from src/esphome/core/string_ref.h:11,
                 from src/esphome/core/entity_base.h:5,
                 from src/esphome/components/select/select.h:4,
                 from src/esphome/components/miot/select/miot_select.h:6,
                 from src/esphome/components/miot/select/miot_select.cpp:2:
src/esphome/core/helpers.h:220:3: note: declared here
  220 |   FixedVector(const FixedVector &) = delete;
      |   ^~~~~~~~~~~
src/esphome/components/miot/select/miot_select.cpp:13:45: note: use '-fdiagnostics-all-candidates' to display considered candidates
   13 |     auto options = this->traits.get_options();
      |                                             ^
src/esphome/components/miot/select/miot_select.cpp: In member function 'virtual void esphome::miot::MiotSelect::dump_config()':
src/esphome/components/miot/select/miot_select.cpp:44:43: error: use of deleted function 'esphome::FixedVector<T>::FixedVector(const esphome::FixedVector<T>&) [with T = const char*]'
   44 |   auto options = this->traits.get_options();
      |                                           ^
src/esphome/core/helpers.h:220:3: note: declared here
  220 |   FixedVector(const FixedVector &) = delete;
      |   ^~~~~~~~~~~
src/esphome/components/miot/select/miot_select.cpp:44:43: note: use '-fdiagnostics-all-candidates' to display considered candidates
   44 |   auto options = this->traits.get_options();
      |                                           ^
In file included from src/esphome/components/miot/select/miot_select.cpp:1:
src/esphome/components/miot/select/miot_select.cpp:46:75: error: request for member 'c_str' in 'options.esphome::FixedVector<const char*>::at(((size_t)i))', which is of non-class type 'const char*'
   46 |     ESP_LOGCONFIG(TAG, "    %i: %s", this->mappings_.at(i), options.at(i).c_str());
      |                                                                           ^~~~~
src/esphome/core/log.h:101:101: note: in definition of macro 'esph_log_config'
  101 |   ::esphome::esp_log_printf_(ESPHOME_LOG_LEVEL_CONFIG, tag, __LINE__, ESPHOME_LOG_FORMAT(format), ##__VA_ARGS__)
      |                                                                                                     ^~~~~~~~~~~
src/esphome/components/miot/select/miot_select.cpp:46:5: note: in expansion of macro 'ESP_LOGCONFIG'
   46 |     ESP_LOGCONFIG(TAG, "    %i: %s", this->mappings_.at(i), options.at(i).c_str());
      |     ^~~~~~~~~~~~~
Compiling .pioenvs/smart-humidifier-2/src/esphome/components/number/number_call.cpp.o
*** [.pioenvs/smart-humidifier-2/src/esphome/components/miot/select/miot_select.cpp.o] Error 1
========================= [FAILED] Took 12.19 seconds =========================
```
by ai

Root Cause (analysis)
This issue was analyzed as follows:

In ESPHome 2025.11, traits.get_options() now returns a FixedVector<const char*> instead of a copyable container (previously std::vector<std::string>).

FixedVector has its copy constructor deleted, so code like auto options = this->traits.get_options(); fails to compile.

Each element is a const char*, so calling .c_str() is invalid.

This pattern is not limited to miot_select. Any component using traits.get_options() (e.g. select, number, climate, fan, light) may be affected.

Other components using traits.get_options() should be reviewed and updated in the same way to prevent similar compile failures.
